
all : lab1-1

lab1-1: lab1-1.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-1 -lGL -lm -DGL_GLEXT_PROTOTYPES lab1-1.c GL_utilities.c MicroGlut.c

lab1-2: lab1-2.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-2 -lGL -lm -DGL_GLEXT_PROTOTYPES lab1-2.c GL_utilities.c MicroGlut.c


lab1-4: lab1-4.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-4 -lGL -lm -DGL_GLEXT_PROTOTYPES lab1-4.c GL_utilities.c MicroGlut.c


lab1-5: lab1-5.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-5 -lGL -lm -DGL_GLEXT_PROTOTYPES lab1-5.c GL_utilities.c MicroGlut.c

lab1-6: lab1-6.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-6 -lGL -lm -DGL_GLEXT_PROTOTYPES lab1-6.c GL_utilities.c MicroGlut.c loadobj.c

clean :
	rm lab1-1
	rm lab1-2
	rm lab1-4
	rm lab1-5
	rm lab1-6

